### ISSUE TITLE
Implicit dependency on SB-INTROSPECT

### ISSUE THREAD

**Issue by quicklisp** [jollheef/cl-logic#1]
I get this when building in a plain SBCL session:

```
;   READ error during COMPILE-FILE: Package SB-INTROSPECT does not exist
```

This can be fixed by adding something like #+sbcl :sb-introspect to the  :depends-on clause in the system definition.

**Comment by jollheef** [comment]
Fix, but not tested.

(On version SBCL 1.0.57.0.debian bug does not occured.)
